### ISSUE TITLE
deploy Rasa

### ISSUE THREAD

**Issue by rngShard** [rngShard/tuk.mensa-kl-conv-ai#17]
See [RasaDoc](https://rasa.com/docs/platform/dev/installation/) ff.

Nvmd, is enterprise version. Api-keyword argument in rasa core run allows HTTP access of manual deployment though.

**Comment by rngShard** [comment]
Note: running current state as working locally now on vm: "cannot find module src.recommender.recommender" in custom action (...)

**Comment by rngShard** [comment]
Endpoint for webhook of telegram expected to be Rasa-Core deployment on webhooks/telegram/webhook (~), where deployment needs to be adressed with proper *domain-name* and *https*.

--> We'd need to setup https domain in gcloud

**Comment by konstikloster** [comment]
Die Webhooks für Telegram und Facebook können wir in einer Google Cloud Function laufen lassen. Die abstrahieren den gesamten Server Kram und wir können uns auf die Kernfunktion des Webhooks konzentrieren. Das kann ich dir am Montag zeigen.

**Comment by rngShard** [comment]
deploy rasa (where currently rasa_core.run is being exec.; how to deploy module run as script??)

**Comment by konstikloster** [comment]
das sollten wir in einer google instance laufen lassen können.
