### ISSUE TITLE
Setup DB on Google Cloud replacing CSVs

### ISSUE THREAD

**Issue by rngShard** [rngShard/tuk.mensa-kl-conv-ai#3]

**Comment by konstikloster** [comment]
Hab mich mit Firebase Firestore beschäftigt und habe dort eine NoSQL Datenbank für das Projekt eingerichtet. Ich weiß jetzt auch wie das ganze funktioniert und werde morgen den Scraper anbinden.

**Comment by rngShard** [comment]
Top! Ziehe mir nachher noch nen Youtube zu Google cloud rein, dann geht's morgen mit normalization los

**Comment by rngShard** [comment]
--> FireBase
Structure:
`./ mensa / [year] / [month] / [calenderWeek] / day / location / [doc (food)]`

**Comment by konstikloster** [comment]
Habe mich nochmal mit Firebase beschäftigt und ich glaube, dass es einfacher ist, einfach die gescrapten Daten als CSV in einem Google Cloud Bucket zu speichern.

Wenn du auf https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python dem Link "ZUR SEITE "SCHLÜSSEL FÜR DIENSTKONTO ERSTELLEN" WECHSELN" folgst, kannst du dir ein Dienstkonto erstellen für welches du dir ähnlich wie bei Firestore eine json cred Datei erstellen kannst. Diese kannst du "tuk-mensa-kl-conv-ai-storage-buckets.json" nennen und in den cloud_connection Ordner im Projekt ziehen.

**Comment by rngShard** [comment]
Ist das issue soweit done? (koennten es dann closen)
