### ISSUE TITLE
Enrich sparse user-food-rating matrix

### ISSUE THREAD

**Issue by rngShard** [rngShard/tuk.mensa-kl-conv-ai#7]
... such that clustering may be then applied (#6).

Note: _similarity functions_ are expected to be considered alongside the enrichment process (as these simi. fct. will apply on generated user profiles concerning both plain- and enriched user matrix).

**Comment by konstikloster** [comment]
Matrix factorizations especially SVD could help us to get a dense matrix. Good blog post:
http://nicolas-hug.com/blog/matrix_facto_1

**Comment by rngShard** [comment]
Nvmd, was getting RMSEs of 1.4 just now. Though better, that's still a span of +-1.2. Not sure though if we could actually expect something better

**Comment by rngShard** [comment]
Using SVD (see notebook `Matrix enrichment, -generalization.ipynb`) could well approximate know ratings, but would not generalize for users with few ratings.

**Comment by rngShard** [comment]
using collaborative filtering instead
